import matplotlib.pyplot as plt
import numpy as np

t=np.linspace(0 ,2*np.pi,100)
r= 2-2*np.sin(t)+ np.sin(t)*((np.sqrt(np.abs(t)))/(np.sin(t)+1.4))
x = r*np.cos(t)
y = r*np.sin(t)
plt.plot(t , x,linewidth=3, color='w',markersize =9, label = 'x= r cos(t)')
plt.plot(t , y,linewidth=3, color='b',markersize =9, label = 'y= r sen(t)')
plt.legend()
plt.title('x= t+2sin(2t), y=t+2cos(5*t)$')
plt.xlabel('Eje x', fontsize = 10)
plt.xlabel('Eje y', fontsize = 10)
a = plt.gca()
plt.fill_between(x,y,color='r')
a.set_facecolor('k')
plt.grid(True)
plt.fill_between(t,x,y,color='r')
plt.axis('equal')
plt.axis('off')
plt.savefig('parte5.png')